version: '3'
services:
  redis:
    image: "redis:alpine"
  kafka:
    environment:
      - "ADVERTISED_HOST=localhost"
      - "ADVERTISED_PORT=9092"
    ports:
      - "2181:2181"
      - "9092:9092"
    image: "spotify/kafka"
  mongodb:
    ports:
      - "27017:27017"
    image: "mongo:3.4"